blank_issues_enabled: false
contact_links:
  - name: VMware Validated Solutions
    url: https://vmware.com/go/vvs
    about: VMware Validated Solutions are technical validated implementations built and tested by VMware and VMware Partners, designed to help customers solve common business problems using VMware Cloud Foundation as the foundational infrastructure.
  - name: VMware Cloud Foundation Product Documentation
    url: https://vmware.com/go/vcf-docs
    about: Manage VM and container-based workloads with the hybrid cloud platform, built on full stack hyper-converged infrastructure.